# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ifd_tool_qt.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_renderTool(object):
    def setupUi(self, renderTool):
        renderTool.setObjectName(_fromUtf8("renderTool"))
        renderTool.resize(783, 821)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/publishIcon.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        renderTool.setWindowIcon(icon)
        renderTool.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(renderTool)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.render_list = QtGui.QTreeWidget(self.centralwidget)
        self.render_list.setMinimumSize(QtCore.QSize(765, 0))
        self.render_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.render_list.setAlternatingRowColors(True)
        self.render_list.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.render_list.setIndentation(8)
        self.render_list.setWordWrap(False)
        self.render_list.setHeaderHidden(False)
        self.render_list.setColumnCount(8)
        self.render_list.setObjectName(_fromUtf8("render_list"))
        self.render_list.header().setDefaultSectionSize(60)
        self.render_list.header().setHighlightSections(False)
        self.verticalLayout.addWidget(self.render_list)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.file_path_entry = QtGui.QLineEdit(self.centralwidget)
        self.file_path_entry.setDragEnabled(True)
        self.file_path_entry.setObjectName(_fromUtf8("file_path_entry"))
        self.gridLayout.addWidget(self.file_path_entry, 0, 1, 1, 5)
        self.version_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.version_label.setFont(font)
        self.version_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.version_label.setObjectName(_fromUtf8("version_label"))
        self.gridLayout.addWidget(self.version_label, 1, 0, 1, 1)
        self.file_path_label = QtGui.QLabel(self.centralwidget)
        self.file_path_label.setMinimumSize(QtCore.QSize(81, 0))
        self.file_path_label.setMaximumSize(QtCore.QSize(81, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.file_path_label.setFont(font)
        self.file_path_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.file_path_label.setObjectName(_fromUtf8("file_path_label"))
        self.gridLayout.addWidget(self.file_path_label, 0, 0, 1, 1)
        self.processors_entry = QtGui.QLineEdit(self.centralwidget)
        self.processors_entry.setMinimumSize(QtCore.QSize(88, 0))
        self.processors_entry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.processors_entry.setDragEnabled(True)
        self.processors_entry.setObjectName(_fromUtf8("processors_entry"))
        self.gridLayout.addWidget(self.processors_entry, 5, 1, 1, 1)
        self.browse_button = QtGui.QPushButton(self.centralwidget)
        self.browse_button.setMinimumSize(QtCore.QSize(85, 0))
        self.browse_button.setMaximumSize(QtCore.QSize(85, 16777215))
        self.browse_button.setObjectName(_fromUtf8("browse_button"))
        self.gridLayout.addWidget(self.browse_button, 0, 6, 1, 1)
        self.start_frame_entry = QtGui.QLineEdit(self.centralwidget)
        self.start_frame_entry.setMinimumSize(QtCore.QSize(88, 0))
        self.start_frame_entry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.start_frame_entry.setDragEnabled(True)
        self.start_frame_entry.setObjectName(_fromUtf8("start_frame_entry"))
        self.gridLayout.addWidget(self.start_frame_entry, 2, 1, 1, 1)
        self.verbose_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.verbose_label.setFont(font)
        self.verbose_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.verbose_label.setObjectName(_fromUtf8("verbose_label"))
        self.gridLayout.addWidget(self.verbose_label, 6, 0, 1, 1)
        self.steps_entry = QtGui.QLineEdit(self.centralwidget)
        self.steps_entry.setMinimumSize(QtCore.QSize(88, 0))
        self.steps_entry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.steps_entry.setDragEnabled(True)
        self.steps_entry.setObjectName(_fromUtf8("steps_entry"))
        self.gridLayout.addWidget(self.steps_entry, 4, 1, 1, 1)
        self.version_list = QtGui.QComboBox(self.centralwidget)
        self.version_list.setMinimumSize(QtCore.QSize(185, 0))
        self.version_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.version_list.setObjectName(_fromUtf8("version_list"))
        self.gridLayout.addWidget(self.version_list, 1, 1, 1, 2)
        self.start_frame_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.start_frame_label.setFont(font)
        self.start_frame_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.start_frame_label.setObjectName(_fromUtf8("start_frame_label"))
        self.gridLayout.addWidget(self.start_frame_label, 2, 0, 1, 1)
        self.message_label = QtGui.QLabel(self.centralwidget)
        self.message_label.setMinimumSize(QtCore.QSize(81, 0))
        self.message_label.setMaximumSize(QtCore.QSize(81, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.message_label.setFont(font)
        self.message_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.message_label.setObjectName(_fromUtf8("message_label"))
        self.gridLayout.addWidget(self.message_label, 9, 0, 1, 1)
        self.processors_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.processors_label.setFont(font)
        self.processors_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.processors_label.setObjectName(_fromUtf8("processors_label"))
        self.gridLayout.addWidget(self.processors_label, 5, 0, 1, 1)
        self.verbose_vex_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.verbose_vex_checkbox.setMinimumSize(QtCore.QSize(115, 0))
        self.verbose_vex_checkbox.setMaximumSize(QtCore.QSize(115, 16777215))
        self.verbose_vex_checkbox.setChecked(False)
        self.verbose_vex_checkbox.setObjectName(_fromUtf8("verbose_vex_checkbox"))
        self.gridLayout.addWidget(self.verbose_vex_checkbox, 6, 2, 1, 1)
        self.verbose_nan_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.verbose_nan_checkbox.setMinimumSize(QtCore.QSize(128, 0))
        self.verbose_nan_checkbox.setMaximumSize(QtCore.QSize(128, 16777215))
        self.verbose_nan_checkbox.setObjectName(_fromUtf8("verbose_nan_checkbox"))
        self.gridLayout.addWidget(self.verbose_nan_checkbox, 6, 3, 1, 1)
        self.end_frame_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.end_frame_label.setFont(font)
        self.end_frame_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.end_frame_label.setObjectName(_fromUtf8("end_frame_label"))
        self.gridLayout.addWidget(self.end_frame_label, 3, 0, 1, 1)
        self.steps_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.steps_label.setFont(font)
        self.steps_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.steps_label.setObjectName(_fromUtf8("steps_label"))
        self.gridLayout.addWidget(self.steps_label, 4, 0, 1, 1)
        self.verbose_entry = QtGui.QLineEdit(self.centralwidget)
        self.verbose_entry.setMinimumSize(QtCore.QSize(88, 0))
        self.verbose_entry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.verbose_entry.setDragEnabled(True)
        self.verbose_entry.setObjectName(_fromUtf8("verbose_entry"))
        self.gridLayout.addWidget(self.verbose_entry, 6, 1, 1, 1)
        self.verbose_alfred_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.verbose_alfred_checkbox.setMinimumSize(QtCore.QSize(107, 0))
        self.verbose_alfred_checkbox.setMaximumSize(QtCore.QSize(107, 16777215))
        self.verbose_alfred_checkbox.setChecked(False)
        self.verbose_alfred_checkbox.setObjectName(_fromUtf8("verbose_alfred_checkbox"))
        self.gridLayout.addWidget(self.verbose_alfred_checkbox, 6, 4, 1, 1)
        self.verbose_time_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.verbose_time_checkbox.setMinimumSize(QtCore.QSize(114, 0))
        self.verbose_time_checkbox.setMaximumSize(QtCore.QSize(114, 16777215))
        self.verbose_time_checkbox.setObjectName(_fromUtf8("verbose_time_checkbox"))
        self.gridLayout.addWidget(self.verbose_time_checkbox, 6, 5, 1, 2)
        self.verbosity_off_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.verbosity_off_checkbox.setObjectName(_fromUtf8("verbosity_off_checkbox"))
        self.gridLayout.addWidget(self.verbosity_off_checkbox, 7, 1, 1, 2)
        self.delete_ifd_checkbox = QtGui.QCheckBox(self.centralwidget)
        self.delete_ifd_checkbox.setObjectName(_fromUtf8("delete_ifd_checkbox"))
        self.gridLayout.addWidget(self.delete_ifd_checkbox, 8, 1, 1, 2)
        self.message_entry = QtGui.QLineEdit(self.centralwidget)
        self.message_entry.setDragEnabled(True)
        self.message_entry.setObjectName(_fromUtf8("message_entry"))
        self.gridLayout.addWidget(self.message_entry, 9, 1, 1, 6)
        self.end_frame_entry = QtGui.QLineEdit(self.centralwidget)
        self.end_frame_entry.setMinimumSize(QtCore.QSize(88, 0))
        self.end_frame_entry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.end_frame_entry.setDragEnabled(True)
        self.end_frame_entry.setObjectName(_fromUtf8("end_frame_entry"))
        self.gridLayout.addWidget(self.end_frame_entry, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setMinimumSize(QtCore.QSize(665, 61))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.render_button = QtGui.QPushButton(self.splitter)
        self.render_button.setEnabled(False)
        self.render_button.setMinimumSize(QtCore.QSize(316, 61))
        self.render_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.render_button.setObjectName(_fromUtf8("render_button"))
        self.verticalLayout.addWidget(self.splitter)
        self.progress_bar = QtGui.QProgressBar(self.centralwidget)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName(_fromUtf8("progress_bar"))
        self.verticalLayout.addWidget(self.progress_bar)
        renderTool.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(renderTool)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        renderTool.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(renderTool)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        renderTool.setStatusBar(self.statusbar)

        self.retranslateUi(renderTool)
        QtCore.QMetaObject.connectSlotsByName(renderTool)
        renderTool.setTabOrder(self.render_list, self.file_path_entry)
        renderTool.setTabOrder(self.file_path_entry, self.browse_button)
        renderTool.setTabOrder(self.browse_button, self.version_list)
        renderTool.setTabOrder(self.version_list, self.start_frame_entry)
        renderTool.setTabOrder(self.start_frame_entry, self.end_frame_entry)
        renderTool.setTabOrder(self.end_frame_entry, self.steps_entry)
        renderTool.setTabOrder(self.steps_entry, self.processors_entry)
        renderTool.setTabOrder(self.processors_entry, self.verbose_entry)
        renderTool.setTabOrder(self.verbose_entry, self.verbose_vex_checkbox)
        renderTool.setTabOrder(self.verbose_vex_checkbox, self.verbose_nan_checkbox)
        renderTool.setTabOrder(self.verbose_nan_checkbox, self.verbose_alfred_checkbox)
        renderTool.setTabOrder(self.verbose_alfred_checkbox, self.verbose_time_checkbox)
        renderTool.setTabOrder(self.verbose_time_checkbox, self.verbosity_off_checkbox)
        renderTool.setTabOrder(self.verbosity_off_checkbox, self.delete_ifd_checkbox)
        renderTool.setTabOrder(self.delete_ifd_checkbox, self.message_entry)
        renderTool.setTabOrder(self.message_entry, self.render_button)

    def retranslateUi(self, renderTool):
        renderTool.setWindowTitle(_translate("renderTool", "v3.0 IFD Sequence Render - Lost Boys Studios", None))
        self.render_list.setSortingEnabled(True)
        self.render_list.headerItem().setText(0, _translate("renderTool", "Client", None))
        self.render_list.headerItem().setText(1, _translate("renderTool", "Status", None))
        self.render_list.headerItem().setText(2, _translate("renderTool", "Host", None))
        self.render_list.headerItem().setText(3, _translate("renderTool", "IFD", None))
        self.render_list.headerItem().setText(4, _translate("renderTool", "Start Time", None))
        self.render_list.headerItem().setText(5, _translate("renderTool", "Progress", None))
        self.render_list.headerItem().setText(6, _translate("renderTool", "Select", None))
        self.render_list.headerItem().setText(7, _translate("renderTool", "Options", None))
        self.version_label.setText(_translate("renderTool", "Version", None))
        self.file_path_label.setText(_translate("renderTool", "IFD File", None))
        self.browse_button.setText(_translate("renderTool", "Browse", None))
        self.verbose_label.setText(_translate("renderTool", "Verbose", None))
        self.start_frame_label.setText(_translate("renderTool", "Start Frame", None))
        self.message_label.setText(_translate("renderTool", "Message", None))
        self.processors_label.setText(_translate("renderTool", "Processors", None))
        self.verbose_vex_checkbox.setText(_translate("renderTool", "VEX Profiling", None))
        self.verbose_nan_checkbox.setText(_translate("renderTool", "NAN Detection", None))
        self.end_frame_label.setText(_translate("renderTool", "End Frame", None))
        self.steps_label.setText(_translate("renderTool", "Steps", None))
        self.verbose_alfred_checkbox.setText(_translate("renderTool", "Alfred Style", None))
        self.verbose_time_checkbox.setText(_translate("renderTool", "Time Stamps", None))
        self.verbosity_off_checkbox.setText(_translate("renderTool", "Verbosity Off", None))
        self.delete_ifd_checkbox.setText(_translate("renderTool", "Delete IFDs", None))
        self.render_button.setText(_translate("renderTool", "Render", None))

